name: Cypress Component Tests

on:
  push:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16  # Use the version of Node.js you want

      - name: Install Dependencies
        run: npm install

      - name: Run Cypress Component Tests
        run: npm run test:components
